### ISSUE TITLE
Unity freezing after first play in .Net 4.X

### ISSUE THREAD

**Issue by ElGognolo** [carmines/UnityPluginCollection#2]
Hello,
I have encountered an issue using your pdfloader plugin :

This is a 100% repro bug:
When Using a release version of the DLL in your sample project
After switching from .Net 3.5 to .Net 4.X
Press play button to load a PDF, that works correctly

Stop play and start playing again, notice Unity freeze and you have to restart it

**Comment by carmines** [comment]
that code will have to be updated to the more recent changes I am using in the camera capture plugin
