### ISSUE TITLE
Unnable to build to UWP

### ISSUE THREAD

**Issue by Nuno-Monteiro** [carmines/UnityPluginCollection#9]
Hello!
Super excited about this repo and being able to access camera stream on HLL2.
I managed to compile the dll's for all architectures (altough I had to edit UWP.vcproj and delete the requires module line about Cpp.WinRT)
However I'm having a very weird issue building the UWP proj from Unity (2019.4.1f1).

The error is:
IOException: Failed to copy C:\Program Files\Unity\Hub\Editor\2019.4.1f1\Editor\Data\il2cpp\external\bdwgc\libatomic_ops\src\atomic_ops\sysdeps\loadstore\char_acquire_release_volatile.h to C:\Users\NunoMonteiro\Documents\test\UnityPluginCollection-master\CameraCapture\CameraCapture\UnitySample\CameraCaptureApp\Temp\StagingArea\Il2CppOutputProject\IL2CPP\external\bdwgc\libatomic_ops\src\atomic_ops\sysdeps\loadstore\char_acquire_release_volatile.h: The system cannot find the path specified.

The most bizarre thing is that if I copy and paste this path on explorer I can open the file!

Did you ever get this issue? What am I doing wrong?

Cheers!

**Comment by cwule** [comment]
Instead of removing Cpp.WinRT, download [this ](https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264) and then build again.

**Comment by mindfreaak** [comment]
as @cwule said, try to download the C++/WinRT extension. if that did not reslove the issue try these steps:
- take the project to a different location that has a very short path.
- check your disk capacity
- check if the file is accessible (avoid working in preserved locations)

**Comment by carmines** [comment]
correct, you should be on the latest VS2019 and ensure you have the cppwinrt extension installed from Visual Studio. There is also a Nuget package that you may not have. Right-click the solution and select "Manage Nuget Package"
